### ISSUE TITLE
Businesses Rules will not be publish for multiple endpoints.

### ISSUE THREAD

**Issue by janithcmw** [wso2/api-manager#1054]
### Description

Business rule siddhi applications will not be published when two worker nodes are added as the business-rule endpoints. The publication will only happen for the 1st node which is added to the configurations. Please refer to the sample configurations below.

```
wso2.business.rules.manager:
  datasource: BUSINESS_RULES_DB
  # rule template wise configuration for deploying business rules
  deployment_configs:
    -
     # <IP>:<HTTPS Port> of the Worker node
     localhost:9444:
       # UUIDs of rule templates that are needed to be deployed on the node
       - stock-data-analysis
       - stock-exchange-input
       - stock-exchange-output
       - identifying-continuous-production-decrease
       - popular-tweets-analysis
       - http-analytics-processing
       - message-tracing-source-template
       - message-tracing-app-template
    -
     localhost:9445:
       # UUIDs of rule templates that are needed to be deployed on the node
       - stock-data-analysis
       - stock-exchange-input
       - stock-exchange-output
       - identifying-continuous-production-decrease
       - popular-tweets-analysis
       - http-analytics-processing
       - message-tracing-source-template
       - message-tracing-app-template
  # credentials for worker nodes
  username: admin
  password: admin
```
Best Regards,
Janith.

### Steps to Reproduce

Add the suggested configuration block after starting two worker profiles and only the 1st node will receive the siddhi app deployment request from the business-rule portal.

### Affected Component

Analytics

### Version

3.2.0

### Environment Details (with versions)

N/A
