### ISSUE TITLE
[APICTL] How to deploy environment specific API via vcs deploy with only one repository?

### ISSUE THREAD

**Issue by TomasTokaMrazek** [wso2/api-manager#1601]
### Description

According to [this](https://medium.com/api-integration-essentials/say-hello-to-the-revolutionized-git-integration-with-apictl-4-0-0-c9ebb05b1a6) article, support for environment specific deployment was removed in 4.0.0 version.

> But doing this method has a pitfall as well. In apictl 3.2.x, the api_params.yaml was included in the API project repository. So that, even though you had only the Source Repository in 3.2.x, you were able to edit the api_params.yaml inside the API project if needed and those changes will be automatically pushed via the “apictl vcs deploy” command. But, in apictl 4.0.0, the params file will not be included inside the API/API Product project repository. Hence, if you tend to use only the Source repository, you will not be able to push the changes in the params file.

Do I understand correctly, that if I want to use `apictl vcs deploy` command to deploy environment specific API, I am forced to use two different git repositories?

I tried to cheat the software, using only one repository with one `vcs.yaml` file and specifying source and deployment repository as different directories.

```
config:
  http_request_timeout: 120000
  export_directory: /home/<redacted>/.wso2apictl/exported
  kubernetes_mode: false
  token_type: JWT
  vcs_deletion_enabled: true
  vcs_config_file_path: /home/<redacted>/ApiManagement/vcs_config.yaml
  vcs_source_repo_path: /home/<redacted>/ApiManagement/api-sources
  vcs_deployment_repo_path: /home/toka/<redacted>/ApiManagement/api-deployments
  tls-renegotiation-mode: never
```

I wasn't successfull with this approach, as subdirectories are probably ignored and .git root is used instead. This results in duplicate deployment where I think both apis acts as a `source`. If I stopped the command in execution and let only the first API deployed, no environment specific parameters were deployed.

```
$ apictl vcs status -e dev
Projects to Deploy (2)

APIs (2) ...
1: [save]		DeploymentArtifact_ASDX-Test-v1: (api-deployments/DeploymentArtifact_ASDX-Test-v1)
2: [save]		ASDX-Test-v1: (api-sources/ASDX-Test-v1)
```

Even if I ignore the duplicity, this is unexpected behaviour. According to [documentation](https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/api-controller/cicd-using-cli/#a-promoting-apis-in-a-git-repository-to-upper-environments-via-cicd) deployment repo should have priority.

> During the vcs deploy, if the api_meta.yaml is inside both the source API project and the individual deployment repository, the priority will be given to the file that is inside the individual deployment repository.

Does that mean, that if I want to deploy API through CI/CD with specific environment properties, I need to:
A) Create separate repo.
B) Write complex script to iterate manually specified APIs and use `apictl import api -f xxx --params params.yaml`.

Am I missing something? If that's the case, I am sorry, but this is completely absurd prerequisity. Adding another git repo to maintain just for this feature is absolutely useless overhead which I do **NOT** want to introduce to my team.

### Affected Component

APICTL

### Version

4.0.2

### Environment Details (with versions)

API Management 4.0.0
APICTL 4.0.2
