### ISSUE TITLE
Can not deploy Kubernetes artifacts with Apple M1 

### ISSUE THREAD

**Issue by SavinduDimal** [wso2/api-manager#1622]
### Description

Getting the following error while trying to deploy Kubernetes artifacts for APIM 4.1.0 and APIM 4.2.0 with Mac m1.

![Screenshot 2023-03-14 at 16 58 08](https://user-images.githubusercontent.com/55122994/224987352-b57db384-c93d-42e7-814b-06528c358021.png)

### Steps to Reproduce

**For APIM 4.1.0**
- Clone [[1]](https://github.com/wso2/kubernetes-apim/tree/4.1.x) and checkout to `4.1.x` branch
- Get the prerequisites as in [[2]](https://github.com/wso2/kubernetes-apim/blob/4.1.x/simple/am-single/README.md)
- Start minikube
- Navigate to `<kubernetes-apim-dir>/simple/am-single` in a terminal
- Use the following commands to deploy Kubernetes artifacts
   - `helm dependency build`
   - `helm install am-single .`
- Check Kubernetes pods
   - `kubectl get pods`
   - `kubectl describe pod <wso2am-mysql-db-service-pod-name>` 

**For APIM 4.2.0**
- Checkout to `4.2.x` branch
- Change `<kubernetes-apim-dir>/simple/am-single/requirements.yaml` as follows
```
dependencies:
  - name: mysql-am
    version: "4.2.0-1"
    repository: "file://../../advanced/mysql-am"
    condition: wso2.deployment.dependencies.cluster_mysql
  - name: nfs-server-provisioner
    version: "1.1.0"
    repository: "https://helm.wso2.com"
    condition: wso2.deployment.dependencies.nfsServerProvisioner
```
- Follow the rest of the steps as in `4.1.0`

[1] - https://github.com/wso2/kubernetes-apim/
[2] - https://github.com/wso2/kubernetes-apim/blob/4.1.x/simple/am-single/README.md

### Affected Component

APIM

### Version

4.1.0, 4.2.0

### Environment Details (with versions)

macOS (Apple M1 Pro)
