### ISSUE TITLE
Add/Override additionalProperties to the params.yaml file when importing the APIs using the apictl tool

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/api-manager#1862]
### Description

Hi Team,

We need to cater to the requirement of supporting adding additional Properties to the params.yaml file which can be used to override the additionalProperties of the exported APIs when importing it to the new environment (Similar to overriding the production/sandbox urls using the params.yaml file).

According to the documentation[1], there is no parameter to set the additionalProperties to the params.yaml file. We tested the scenario by adding the filling entry to the params.yaml file, but it was not successful.

```
environments:
    - name: test
      configs:
          additionalProperties:
              - name: test1
                value: http://name1
                display: true
              - name: test2
                value: http://name2
                display: true
```

Therefore, could you please let us know the possibility of providing the feature to add the addionalProperties to the params.yaml file?

[1] https://apim.docs.wso2.com/en/4.0.0/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters/
Thanks,
Siluni

requirement

### Steps to Reproduce

N/A

### Affected Component

APIM

### Version

4.0.0
