### ISSUE TITLE
Dynamic Data with apictl - Endpoint for Third Party API

### ISSUE THREAD

**Issue by VinulaUthsara** [wso2/api-manager#2113]
### Problem

Currently there is no option to to parameterize by environment with apictl tool the parameter "Api external production endpoint" available for the third party apis.

### Solution

Requesting an improvement to parameterize the "Api external production endpoint" parameter available for third party APIs when using the apictl tool.

To parameterize the environment with the apictl tool using the params file, the "apiExternalProductionEndpoint" parameter of this configuration.

```
advertiseInfo:
    advertised: true
    apiExternalProductionEndpoint: 
    apiExternalSandboxEndpoint:
    originalDevPortalUrl: 
    apiOwner: 
    vendor: 
```

For example, for a production endpoint of the development environment, we have this configuration in the params file:

```
environments:
  - name: development
   configs:
     endpoints:
       production:
         url: https://<hostname>:9443

```
We wish to do the same but to configure the environment parameter "apiExternalProductionEndpoint" for a third party API.

### Affected Component

APICTL

### Version

4.1.0

### Suggested Labels

4.1.0
