### ISSUE TITLE
Cannot save circuit breakers for the API - APIM 4.0.0 with CC 1.0.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/api-manager#2280]
### Description

Cannot add the circuit breaker configurations [1] to the API definition via the publisher portal since those are not getting saved properly.

[1] https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/resiliency/circuit-breakers/#enable-circuit-breakers-for-api-endpoints

### Steps to Reproduce

- Start the pack and go to the publisher portal.
- Create a test API.
- Then click on the **API Definitions**.
- Try to update the definition by adding the content which is in the documentation [1].
```
x-wso2-production-endpoints:
  urls:
  - https://localhost:2380/v3
  advanceEndpointConfig:
    circuitBreakers:
      maxConnections: 1024
      maxRequests: 75
      maxPendingRequests: 35
      maxConnectionPools: 1024
      maxRetries: 3
```

- Save the definition.
- Reload the page and able to see that the added content is not in there.

[1] https://apim.docs.wso2.com/en/4.0.0/deploy-and-publish/deploy-on-gateway/choreo-connect/endpoints/resiliency/circuit-breakers/#enable-circuit-breakers-for-api-endpoints

### Affected Component

APIM

### Version

4.0.0
