### ISSUE TITLE
[APICTL-4.1.0] No error message occurs when using apictl to import an API with incorrectly formatted params.yaml

### ISSUE THREAD

**Issue by SameeraSI** [wso2/api-manager#2389]
### Description

When using APICTL to modify an existing API with an exported zip file of that API along with a params.yaml, the APICTL indicates a success message. However, the structure of the params.yaml file used differs from the structure outlined in the documentation [1].

The code below is used within the params.yaml file:
```
environments:
  - name: dev
    endpoints:
      production:
          url: https://www.abc.com:8096/test/test
      sandbox:
          url: https://www.abc.com:8096/test/test
      sessionManagement: transport
      sessionTimeOut: 120000
    deploymentEnvironments:
      - displayOnDevportal: true
        deploymentEnvironment: Default
        deploymentVhost: test.com
```

If the above mentioned code is used in the params.yaml file to update an API with the API zip file, the endpoints will be modified to localhost.
<img width="524" alt="296201603-80e83d0b-8207-4c1c-864b-2b5369a38107" src="https://github.com/wso2/api-manager/assets/93453763/bd471b11-f92c-4ea1-bad1-e603db1437f0">

However, APICTL indicates a success message instead of giving an error. 
<img width="732" alt="296201412-d0188a6a-3111-4b9f-a960-63d886d40568" src="https://github.com/wso2/api-manager/assets/93453763/b5790931-d55f-4882-a47b-c654581fd90b">

The corrected params.yaml code should be as follows,
```
environments:
 - name: dev
   configs:
     endpoints:
       production:
           url: https://www.abc.com:8096/test/test
       sandbox:
           url: https://www.abc.com:8096/test/test
       sessionManagement: transport
       sessionTimeOut: 120000
     deploymentEnvironments:
       - displayOnDevportal: true
         deploymentEnvironment: Default
         deploymentVhost: test.com
```
In tested params.yaml code, the ”configs:”  line is missing.

This needs to be fixed since it should throw an error on the APICTL tool while updating an API with an invalid params.file 

[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters/#defining-the-parameters-file-for-an-api

### Steps to Reproduce

Deployed the PizzaShack API from the Publisher Portal and the endpoints of the PizzaShack API were as follows,
<img width="525" alt="296200356-1e5f392b-a434-4399-be93-7b7b32fe3850-1" src="https://github.com/wso2/api-manager/assets/93453763/5802f2d8-781d-499b-a915-9fb17c086d6d">
Then exported PizzaShack API with APICTL.

Then we created a params.yaml file using the below code,
```
environments:
  - name: dev
    endpoints:
      production:
          url: https://www.abc.com:8096/test/test
      sandbox:
          url: https://www.abc.com:8096/test/test
      sessionManagement: transport
      sessionTimeOut: 120000
    deploymentEnvironments:
      - displayOnDevportal: true
        deploymentEnvironment: Default
        deploymentVhost: test.com
```
In the next step, we used the above params.yaml file and the previously expoted API zip file to update the PizzaShack API using the following command in APICTL,
`apictl import api -f PizzaShackAPI_1.0.0.zip -e dev -k --params params.yaml --preserve-provider=false --rotate-revision --update=true --verbose`

The APICTL showed “Response : API imported successfully. Successfully imported API”. A screenshot is below,
<img width="732" alt="296201412-d0188a6a-3111-4b9f-a960-63d886d40568-2" src="https://github.com/wso2/api-manager/assets/93453763/bddaa34d-5c06-436f-832b-11ff0df53bfa">

Because of above step the API endpoints were changed as follows to localhost instead of defined value in the params.file,
<img width="524" alt="296201603-80e83d0b-8207-4c1c-864b-2b5369a38107" src="https://github.com/wso2/api-manager/assets/93453763/43874dbe-ea9e-4dce-9fc7-2b22b4cb003a">

Additionally the correct params.yaml template should be as follows,
```
environments:
 - name: dev
   configs:
     endpoints:
       production:
           url: https://www.abc.com:8096/test/test
       sandbox:
           url: https://www.abc.com:8096/test/test
       sessionManagement: transport
       sessionTimeOut: 120000
     deploymentEnvironments:
       - displayOnDevportal: true
         deploymentEnvironment: Default
         deploymentVhost: test.com
```

Then we updated the same PizzaShack API using corrected params.yaml file along with API zip using APICTL. The api APICTL showed as “Response : API imported successfully.Successfully imported API.” as below,
<img width="715" alt="296202091-e458371e-dd08-40a5-a965-362b8753f2d4" src="https://github.com/wso2/api-manager/assets/93453763/dc642290-d3bd-434e-acb9-0aa6be18ffa8">

Also the API endpoints were updated correctly,
<img width="685" alt="Screenshot 2024-01-17 at 13 55 46" src="https://github.com/wso2/api-manager/assets/93453763/339ab9d0-aa38-4991-bad8-f1ae19d16d8b">

### Affected Component

APICTL

### Version

4.1.0
