### ISSUE TITLE
Distribution of API Developer Portal

### ISSUE THREAD

**Issue by piyumaldk** [wso2/api-manager#3343]
### Description

The task is to determine the most suitable approach for distributing the API Developer Portal, focusing on efficiency and minimising platform dependencies. This involves exploring, implementing, and testing various methods to finalise the best distribution strategy.

### Affected Component

None

**Comment by piyumaldk** [comment]
### Update [2024-11-06]

- Participated meeting `Dev Portal Plan @10.30AM to 11.00AM`
   - Decided to assign me to $Subject task in the meeting
   
- Had a discussion after the meeting with UI/UX APIM Lead to discuss the objective of the task

- Setup repo: https://github.com/wso2/api-developer-portal
    - **Noticed below key facts while doing the setup**
    - Postgres is required to run the product (Follow the pgAdmin 4 flow)
    - Later java version is required to run the product (Was't able to run with java11, had to switch java17)
    - devportal core: https://github.com/wso2/api-developer-portal-core is imported to devportal as a node module which is a decent practice

- In the morning discussion, a concern of user having all the modules (Including core related modules) when user is installing core node module was raised.
   - Since devportal only had core as the dependency, decided to try with packaging (pkg) to get rid of dependencies.
   
- When packaging after required changes (starting points of executable file as app.js, multi-tenant.js, and single-tenant.js, we can get executable files but concern is they are not os independent. Due to this, generated linux, mac, and windows files.
   - Compared the executable files (~40mb) with dev portal node module size (~500mb). Considering the sizes, packaging was promising.
   
- Studied the devportal code and found out 
   - startup.sh is running when running the project.
   - In the script, depending on the situation, multi and single tenant related js in executing.
   ```
   if [ "$tenant" == "single" ] || [ "$tenant" == "dev" ]; then
       npm run build-css --watch & node ../node_modules/devportal-webapp/src/single-tenant.js
   else
      node ../node_modules/devportal-webapp/src/multi-tenant.js
   fi
   ```
   - Change the script to run generated executable files
   ```
   # Check the OS
  OS=$(uname -s)
  
  # Path to the bundled executables
  BIN_DIR="./devportal-webapp"
  
  # Set executable file based on OS
  case "$OS" in
    "Darwin")
      EXECUTABLE="$BIN_DIR/devportal-webapp-macos"
      ;;
    "Linux")
      EXECUTABLE="$BIN_DIR/devportal-webapp-linux"
      ;;
    CYGWIN*|MINGW*)
      EXECUTABLE="$BIN_DIR/devportal-webapp-win.exe"
      ;;
    *)
      echo "Unsupported OS: $OS"
      exit 1
      ;;
  esac
  
  # Run the correct tenant mode with CSS watch
  if [ "$tenant" == "single" ] || [ "$tenant" == "dev" ]; then
    npm run build-css --watch & exec "$EXECUTABLE" single-tenant
  else
    exec "$EXECUTABLE" multi-tenant
  fi
   ```
   
- While testing, notice that watcher is requiring below modules, hence wasn't able to get rid of the whole node modules.
   - chokidar
   - fs-extra
   
- Even after installing both, product fails while finding `express`
   - In theory, packing should include required node modules, it seems it has missed express. Found out that this can happen because pkg sometimes fails to recognize dynamically required modules.
   
TODO: Try adding express related modules manually to packaging and test

**Comment by piyumaldk** [comment]
### Update [2024-11-07]

- Change the pkg settings like below to include all the required files and modules
```
"bin": {
    "devportal-webapp": "src/app.js",  
    "multi-tenant": "src/multi-tenant.js",
    "single-tenant": "src/single-tenant.js"
  },
  "pkg": {
  "scripts": [
    "**/*.js"
  ],
  "assets": [
    "src/**/*",       
    "package.json",  
    "watcher.js"      
  ],
  "targets": [
    "node16-linux-x64",
    "node16-macos-x64",
    "node16-win-x64"
  ],
  "outputPath": "dist"
  }
```

   - This solved the above issue but executable files will become around ~200mb. Since we have 3 files for 3 operating systems, size wise, npm nodules will be lighter (Due to the duplication of executable files)
   
- When running the devportal with executable files, faced an issue.
   - When investigating the issue, noticed that in core module, we have used relative paths (for example: '../../../../src/')
   - This ideally tells the code to refer outside the node modules and in the devportal 
   - This has been referred in multiple places which is a problem (With the current core, we cannot move to pkg packaging because it will manipulate the file structure which will eventually results ENOENT
   
-

**Comment by piyumaldk** [comment]
### Update [2024-11-08]

- Debugged above issue.
   - Found out that this is because of some paths try to access the inside of node module. 
   - Since changing all the paths, this looks troublesome so focused on new methods.
   
- Found out about below methods.
   - Nexe
   - Webpack with Node File System (fs) Plugin
   - Bytenode
   - Node.js Modules with Docker
   
- From above methods, tried Bytenode. It was more capable of simple or single files so gave up on that approach.

- Docker was initially considered but gave up due to the the fact that user have to depend on Docker.

- Compared Nexe and Webpack and it was said that Webpack is the better solution for the situation on multiple places.

- Tried Webpack apporach including node modules (As the requirement is to get rid of node modules in dev portal)

- Below are the changes made for core to work with Webpack

**webpack.config.js in root**
```
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = {
  mode: 'production',
  stats: {
    errorDetails: true
  },
  entry: {
    // app: './src/app.js',              
    // multiTenant: './src/multi-tenant.js', 
    singleTenant: './src/single-tenant.js' 
  },

  output: {
    path: path.resolve(__dirname, 'dist'), 
    filename: '[name].bundle.js', 
  },

  target: 'node',

  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env'],
          },
        },
      },
    ],
  },

  plugins: [
    new CopyWebpackPlugin({
      patterns: [
        { from: './src/pages/tryout', to: './src/pages/tryout' },
      ],
    }),
  ],

  resolve: {
    extensions: ['.js', '.json'],
    alias: {
      '@src': path.resolve(__dirname, 'src'),
    },
  },
};
```

   - As you can see, node modules were not excluded. 
   - `./src/pages/tryout` contains non js files so they were copied manually with `CopyWebpackPlugin`
   - Add three entries, and commented out 2 as I only need single tenant for testing.
   - Change the mode to `production`
   
**package.json in root**
```
"scripts": {
    "design-mode": "npm run build-css --watch & nodemon src/dev-server.js",
    "devportal": "npm run build-css --watch & nodemon src/app.js",
    "multi-tenant": "npm run build-css --watch & nodemon src/multi-tenant.js",
    "build-css": "node watcher.js",
    "build": "webpack --config webpack.config.js"
  },
"devDependencies": {
    "@babel/core": "^7.26.0",
    "@babel/preset-env": "^7.26.0",
    "babel-loader": "^9.2.1",
    "copy-webpack-plugin": "^12.0.2",
    "webpack": "^5.96.1",
    "webpack-cli": "^5.1.4"
  }
```

   - Webpacck to work, added above dev dependencies. 
   - Added build script to build the webpack
   
- Change the devportal startup script as below
```
if [ "$tenant" == "single" ] || [ "$tenant" == "dev" ]; then
    node ../artifacts/devportal-webapp/singleTenant.bundle.js
else
    node ./artifcats/devportal-webapp/multiTenant.bundle.js
fi
```

- Added the built webpack and resources to the correct path (devportal-webapp) and tested
   - Later removed the watcher to test without node modules (As watcher is using few node modules)
   - Build was broken on multiple places
   
- Debugged and changed the core code accordingly and tested again.
   - Made changes
   
   In src/utils/util
   `var filePrefix = '../../src/';`
   
   In src/single-tenant
   `var filePrefix = '../../src/';`
   `copyStyelSheet('../../../src/');`
   `app.use('/styles', express.static(path.join(__dirname, '../../src/' + '/styles')));`
   `const folderToDelete = path.join(__dirname, '../../src/' + '/styles');`
   
   Note: Other changes are not required as only these files are used with current devportal
   
   - Portal started fine
   - Tried adding an API and it also worked fine
   
TODO: There is a warning in the server like below.
```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```
This needs to be further investigated

**Comment by piyumaldk** [comment]
### Update [2024-11-11]

- Debug the mentioned warning
```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```
   - Warning is happening because core webpack is using MemoryStore, which isn't recommended in production because it can cause memory leaks and won't work well in a multi-process environment.
   - Bug further and found out that, in core, express-session is being used and config like below
```
app.use(session({
    secret: secret,
    resave: false,
    saveUninitialized: true,
    cookie: { secure: false } // Set to true if using HTTPS
}));
```
   - According to sources, we need to add a store to get rid of the issue like `store: new RedisStore({ client: redisClient })`
   - Otherwise it will use MemoryStore
   - However, according to some people in stackoverflow, using a separate store for simple tasks in an overkill. [1]
   - There are another suggestions like changing the implementation to handle proper clean up or using cookie-session instead of express-session. This needs to be fixed before going to production.
   
[1] https://stackoverflow.com/questions/10760620/using-memorystore-in-production

**Comment by piyumaldk** [comment]
exe path - /Users/piyumal/Desktop/forked-apim/api-developer-portal/artifacts/devportal-webapp
after ../.. - /Users/piyumal/Desktop/forked-apim/api-developer-portal

**Comment by piyumaldk** [comment]
### Update [2024-11-13]

- Permission issue is happening because macOS does not trust downloading executable files and it removes the excutable permission. Changing the permission worked.

- Had a meeting about the progress. Asked to change the workflow not to trigger when PR is merged. 
   - Changed the workflow to work when a tag release is done. Tested and worked successfully.
   - Below is the new workflow
   
```
name: Build and Release on Tag Push

on:
  push:
    tags:
      - 'v*'  

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload dist folder as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-output
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dist folder artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-output
          path: ./dist-output  

      - name: Zip each file in dist-output
        run: |
          mkdir -p zipped-output
          for file in ./dist-output/*; do
            filename=$(basename "$file")
            zip -r "zipped-output/$filename.zip" "$file"
          done

      - name: Debug zipped artifact contents
        run: ls -R ./zipped-output  

      - name: Create or Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}  
          name: Release ${{ github.ref_name }}
          body: "Automated release generated on tag push."
          draft: false
          prerelease: false
          artifacts: "./zipped-output/*"  
          allowUpdates: true 

```

- New core changes were received, so started working on building executable file on new core.
   - Came up with UUID module not found error. Installing that fixed the error.
   - Currently fails to load the portal after all the required changes.
   
TODO: Debug and find out the reason of failing the portal
