### ISSUE TITLE
[Gateway Visibility] Restricted Gateways Appear in Dev Portal When Created via `deployment.toml`

### ISSUE THREAD

**Issue by DakshithaS** [wso2/api-manager#3794]
### Description

When configuring multiple gateways using **`deployment.toml`** with restricted **gateway visibility**, unauthorized users should not see the gateway in the **Developer Portal**. However, when the gateway is created using **`deployment.toml`**, users who do not have the assigned roles can still see the **restricted gateway** inside the **Swagger UI (server fields)** in the **Dev Portal**.  

This issue does **not** occur when the gateway is created through the **Admin Portal**, where the expected behavior is preserved.  

<img width="1382" alt="Image" src="https://github.com/user-attachments/assets/0be1ac55-de43-42c7-aab9-758961f75e82" />

### Steps to Reproduce

1. Follow the documentation to create multiple gateways using `deployment.toml`:  
   - [Deploy Through Multiple API Gateways](https://apim.docs.wso2.com/en/4.5.0/deploy-and-publish/deploy-on-gateway/deploy-api/deploy-through-multiple-api-gateways/)  
   - [Configure Gateway Visibility](https://apim.docs.wso2.com/en/4.5.0/administer/multiple-gateways/configure-gateway-visibility/)  

2. Configure **multiple gateways** in **deployment.toml** with visibility restrictions:  

### **APIM Instance 1 (Control Plane)**  
```toml
[[apim.gateway.environment]]
name = "Production Gateway"
type = "hybrid"
visibility = ["role-1","role-2","role-3"]
gateway_type = "Regular"
provider = "wso2"
display_in_api_console = true
description = "This is a hybrid gateway that handles both production and sandbox token traffic."
show_as_token_endpoint_url = true
service_url = "https://localhost:9444/services/"
username= "${admin.username}"
password= "${admin.password}"
ws_endpoint = "ws://localhost:9099"
wss_endpoint = "wss://localhost:8099"
http_endpoint = "http://localhost:8281"
https_endpoint = "https://localhost:8244"
websub_event_receiver_http_endpoint = "http://localhost:9021"
websub_event_receiver_https_endpoint = "https://localhost:8021"
```

### **APIM Instance 2 (Offset 1)**  
```toml
[apim.sync_runtime_artifacts.gateway]
gateway_labels =["Production Gateway"]
```

```toml
[[apim.throttling.url_group]]
traffic_manager_urls = ["tcp://localhost:9611"]
traffic_manager_auth_urls = ["ssl://localhost:9711"]
```

```toml
[apim.throttling]
service_url = "https://localhost:9443/services/"
throttle_decision_endpoints = ["tcp://localhost:5672"]
```

```toml
[apim.key_manager]
service_url = "https://localhost:9443/services/"
username = "$ref{super_admin.username}"
password = "$ref{super_admin.password}"
```

3. Deploy an API to the "Production Gateway"
- Create an API and deploy it to the "Production Gateway".
- Publish the API.

4. Attempt to Invoke the API via the Dev Portal
- Log in to the Developer Portal with a user who does NOT have role-1, role-2, or role-3.
- Go to the API's Try Out (Swagger UI) section.
- Observe that the restricted gateway still appears in the server fields, even though it should not be visible.

#### **Expected Behavior** 
✅ Users who do not belong to role-1, role-2, or role-3 should not see the restricted gateway in the Swagger UI.
✅ Users without proper roles should not be able to invoke APIs through the restricted gateway in the Developer Portal.

#### **Observed Issue**
❌ Users without the assigned roles can still see the restricted gateway in the Swagger UI (server fields).
❌ This issue only occurs when the gateway is created using deployment.toml.
✅ When the gateway is created through the Admin Portal, the expected behavior is preserved (i.e., unauthorized users cannot see the restricted gateway).

### Version

4.5.0 RC2
