### ISSUE TITLE
Enable securityScheme configured in OAS to populate and honor in API creation and update

### ISSUE THREAD

**Issue by Sarangan0219** [wso2/api-manager#556]
### Problem

Even if we use a valid OAS with API-Key authentication configured, after importing it to the API publisher, it results in only the 'OAuth2' authentication mechanism enabled and 'Api Key' is disabled API.
 
```
 securitySchemes:
   default:
     type: apiKey
     in: header       # must be "header"
     name: apikey
     flows:
       implicit:
         authorizationUrl: 'https://test.com/'
         scopes: {}
```
 
In API level
```
security:
 - default: []
```
 
In all resources
```
     x-wso2-application-security:
       security-types:
         - api_key
       optional: false
```
 
With this approach, even if we use a valid OAS with API-Key authentication configured, after importing it to the API publisher, it results in only the 'OAuth2' authentication mechanism enabled and 'Api Key' is disabled API.
 
**Steps to reproduce the issue**
 
- Publish the sample pizzshark API from the publisher portal.
- Select the API Key as the Application level security of this pizzshark API using the publisher portal UI and save the changes.
- Open the open API definition and the security type has been changed to API Key as mentioned above. 
- Download the open API definition.
- Create a new API by uploading the downloaded Open-API definition. 
- Check the  Application level security, it will be changed into the Oauth2 even though we have configured it as an API key in the open API definition. 

### Solution

 As per our current implementation, the securityScheme configured in OAS is not honored during API creation. We need to fix this.

### Affected Component

APIM

### Version

4.1.0

### Related Issues

https://github.com/wso2-enterprise/wso2-apim-internal/issues/402
