### ISSUE TITLE
Need to provide sample params.yaml files according to the endpoint type when generating the Deployment directory with ctl

### ISSUE THREAD

**Issue by Chamindu36** [wso2/api-manager#844]
At the moment, we use the same template file to generate params.yaml file inside the deployment directory for a project with `gen-deployment` command. This needs to be improved to generate endpoint type-specific param files on-demand with suitable default values by introducing an argument to specify endpoint type. 

**Need to add this new flag into the documentation as well.**
Docs : https://apim.docs.wso2.com/en/4.0.0-dev/install-and-setup/setup/api-controller/advanced-topics/configuring-environment-specific-parameters/#generating-the-deployment-directory

Eg: 
`gen deployment-dir - s <source_path> --endpointType rest`

Generated _params.yaml_ file

```
environments:
    - name: <environment_name>
      configs: <multiple_configurations_relevant_to_the_specific_environment>
          endpoints:
              production:
                  url: 'https://prod.wso2.com'
                  config:
                      retryTimeOut: <no_of_retries_before_suspension>
                      retryDelay: <retry_delay_in_ms>
                      factor: <suspension_factor>
              sandbox:
                  url: 'https://dev.wso2.com'
                  config:
                      retryTimeOut: <no_of_retries_before_suspension>
                      retryDelay: <retry_delay_in_ms>
                      factor: <suspension_factor>
          security:
              production:
                  enabled: <whether_security_is_enabled_for_production_endpoint>
                  type: <endpoint_authentication_type_basic_or_digest_for_production_endpoint>
                  username: <endpoint_username_for_production_endpoint>
                  password: <endpoint_password_for_production_endpoint>
              sandbox:
                  enabled: <whether_security_is_enabled_for_sandbox_endpoint>
                  type: <endpoint_authentication_type_basic_or_digest_for_sandbox_endpoint>
                  username: <endpoint_username_for_sandbox_endpoint>
                  password: <endpoint_password_for_sandbox_endpoint>
          deploymentEnvironments:
              - displayOnDevportal: <boolean>
                deploymentEnvironment: <environment_name>        
          certs:
              - hostName: <endpoint_url>
                alias: <certificate_alias>
                path: <certificate_name>
          mutualSslCerts:
              - tierName: <subscription_tier_name>
                alias: <certificate_alias>
                path: <certificate_name>
          policies: 
              - <subscription_policy_1_name>
              - <subscription_policy_2_name>
```
