### ISSUE TITLE
[APIM 3.2.0]Missing j2 mapping for registry.xml

### ISSUE THREAD

**Issue by SupunRandunu** [wso2/api-manager#949]
### Description

 In the registry.xml file, if we need to add handlers with multiple nested property parameters, there are no J2 mapping to achieve this requirement.

```<handler class='org.wso2.carbon.registry.extensions.handlers.WSDLMediaTypeHandler'>```
       ```<property name="disableSymlinkCreation">true</property>```
    ```    <property name="schemaLocationConfiguration" type="xml">```
         ```   <location>/trunk/schemas/</location>            ```
	```</property>```
     ```   <property name="wsdlLocationConfiguration" type="xml">```
       ```     <location>/trunk/wsdls/</location>            ```
	```</property>```
      ```  <property name="policyLocationConfiguration" type="xml">```
           ``` <location>/trunk/policies/</location>            ```
	```</property>```
      ```  <filter class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher">```
            ```<property name="mediaType">application/wsdl+xml</property>```
       ``` </filter>```
    ```</handler>```

### Steps to Reproduce

Check the configurations.

### Affected Component

APIM

### Version

3.2.0

**Comment by binodmx** [comment]
Below is how you should set config in deployment.toml to achieve the requirement.

```toml
##### Registry handler 1 #####
[[registry_handler]]
class="org.wso2.carbon.registry.extensions.handlers.WSDLMediaTypeHandler"
filter_class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher"

[registry_handler.properties]
disableSymlinkCreation = "true"
myprop1= "true"

### parent property 1: schemaLocationConfiguration
[[registry_handler.nested_property]]
enable = true
name = "schemaLocationConfiguration"
type = "xml"

# nested property 1
[[registry_handler.nested_property.schemaLocationConfiguration]]
tag = 'location'
value = "/trunk/schemas/1"
key = "mykey"

# nested property 2
[[registry_handler.nested_property.schemaLocationConfiguration]]
tag = 'location'
value = "/trunk/schemas/2"
key = "mykey2"

# nested property 3
[[registry_handler.nested_property.schemaLocationConfiguration]]
tag = 'newlocation'
value = "/trunk/schemas/3"
key = "mykey3"

## parent property 2: wsdlLocationConfiguration
[[registry_handler.nested_property]]
enable = true
name = "wsdlLocationConfiguration"
type = "xml"

# nested property 1
[[registry_handler.nested_property.wsdlLocationConfiguration]]
tag = 'location'
value = "/trunk/wsdls/"

## parent property 3: policyLocationConfiguration
[[registry_handler.nested_property]]
enable = true
name = "policyLocationConfiguration"
type = "xml"

# nested property 1
[[registry_handler.nested_property.policyLocationConfiguration]]
tag = 'location'
value = "/trunk/policies/"

[registry_handler.filter_properties]
mediaType = "application/vnd.wso2-service+xml"

##### Registry handler 2 #####
[[registry_handler]]
class="org.wso2.carbon.registry.extensions.handlers.ZipWSDLMediaTypeHandle"
filter_class="org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher2"

[registry_handler.properties]
wsdlMediaType = "application/wsdl+xml"
schemaMediaType = "application/xsd+xml"
threadPoolSize = 50
disableSymlinkCreation = true
numberOfRetry = 3

## parent property 1: schemaLocationConfiguration
[[registry_handler.nested_property]]
enable = true
name = "schemaLocationConfiguration"
type = "xml"

# nested property 1
[[registry_handler.nested_property.schemaLocationConfiguration]]
tag = 'location'
value = "/trunk/schemas/1"
key = "mykey"

[registry_handler.filter_properties]
mediaType = "application/vnd.wso2-service+xml"
```
